name: Docker
on: [workflow_dispatch]
jobs:
  docker-job:
    runs-on: ubuntu-latest
    container: 
      image: node:21-alpine3.18
      #credentials:
        #username:
        #password:
      env:
        API_URL : some-url.com
      ports:
        - 80
      #volumes:
      #options: --cpus 1
    steps:
      - name: Log node & OS version
        run: |
          node -v
          cat /etc/os-release
      - name: Log env
        run: echo $API_URL
      - name: Container in a Step
        uses: docker://node:18-alpine3.18
        with:
          entrypoint: /usr/local/bin/node
          args: -p 2+3
      - name: Log node version
        uses: docker://node:18-alpine3.18
        with:
          args: -v