name: Stale issues & PRs

on: 
  schedule:
    - cron: "0 12 * * *"
    - cron: "0/1 * * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - name: stale test
        uses: actions/stale@v8
        with:
          stale-issue-message: "This is some message"
          days-before-stale: 1
          days-before-close: 5

      

