name: Status Check Functions

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: sleep 20
      - name: Runs on Failure
        if: failure()
        run: echo 'Runs only on failure'
      - nane: Runs on Success
        # This is not needed (DEFAULT BEHAVIOUR)
        if: success()
        run: echo "Runs only on Success"
      - name: Always Runs
        if: always()
        run: echo "Always runs"
      - name: Runs when Cancelled
        if: cancelled()
        run: echo "Runs on Cancelled"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    if: failure()
    steps:
      - run: echo "job 2"