name: Status Check Functions

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step1
        run: sleep 20
      - name: Step 2
        id: step-2
        run: exit 1
      - name: Runs on Failure
        if: failure() && steps.step-2.conclusion == 'failure'
        run: echo 'Step 2 has failed'
      - name: Runs on Success
        # This is not needed (DEFAULT BEHAVIOUR)
        if: success()
        run: echo "Runs only on Success"
      - name: Always Runs
        if: always()
        run: echo "Always runs"
      - name: Runs when Cancelled
        if: cancelled()
        run: echo "Runs on Cancelled"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    if: failure()
    steps:
      - run: echo "job 2"